/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CubeCore {
  constructor()
  rotate(operations: string): void
  getStartTime(): number
  reset(): void
  getCube(): number[][][]
  getLastStep(): string
  scramble(steps: number): void
  getSvgBase64Png(): string
  getSvg(): string
  isSolved(): boolean
}
