/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class CubeCore {
  constructor()
  rotate(operations: string): void
  getStartTime(): number
  reset(): void
  getCube(): number[][][]
  getLastStep(): string
}
