name: Publish Python Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.12
      - name: Run image
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.7

      - name: Build package with Poetry
        run: cd nonebot-plugin-cube && poetry build

      - name: Publish package with Poetry
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          cd nonebot-plugin-cube && poetry publish