name: Release Cli

on:
  push:
      tags:
        - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: cube_game-x86_64-pc-windows-msvc.zip
            rustflags: -C target-feature=+crt-static

          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: cube_game-x86_64-unknown-linux-gnu.tar.gz

          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            arch: arm64
            name: cube_game-aarch64-unknown-linux-gnu.tar.gz

          - target: aarch64-apple-darwin
            os: macos-latest
            name: cube_game-aarch64-apple-darwin.tar.gz

          - target: x86_64-apple-darwin
            os: macos-latest
            name: cube_game-x86_64-apple-darwin.tar.gz

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    env:
      RUSTFLAGS: ${{ matrix.rustflags || '' }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install Cross-Compile Support (ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        uses: cyberjunk/gha-ubuntu-cross@v4
        with:
          arch: arm64
          
      - name: Install gcc-aarch64-linux-gnu
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update && sudo apt-get install pkg-config libx11-dev:arm64
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          sudo apt-get update && sudo apt-get install -yq gcc-aarch64-linux-gnu
          echo "JEMALLOC_SYS_WITH_LG_PAGE=16" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          
      - name: Build | Build [Cross]
        if: matrix.os != 'windows-latest'
        env:
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
          PKG_CONFIG_ALLOW_CROSS: 1
        run: |
          cd cube-game
          cargo build --release --locked --target ${{ matrix.target }}

      - name: Build | Build [Cargo]
        if: matrix.os == 'windows-latest'
        run: |
          cd cube-game
          cargo build --release --locked --target ${{ matrix.target }}

      - name: Post Build | Prepare artifacts [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd cube-game/target/${{ matrix.target }}/release
          7z a ../../../../${{ matrix.name }} cube-game.exe

      - name: Post Build | Prepare artifacts [-nix]
        if: matrix.os != 'windows-latest'
        run: |
          cd cube-game/target/${{ matrix.target }}/release
          tar czvf ../../../../${{ matrix.name }} cube-game

      - name: Release | Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

      - name: Create Release Draft and Upload Artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.name }}
